import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Auth from "../components/Auth";

const Home: NextPage = () => {
  return (
    <div className={"bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Social Poll
        </h1>

          <div className={"mt-16"}
              >

              <button className="btn btn-ghost">HOW TO USE?</button>
              <button className="btn btn-secondary">CREATE POLL</button>


          </div>


      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
